# Generated by Django 4.1.3 on 2022-11-07 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_delete_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pay_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='firstApp.payplan'),
        ),
    ]
