# Generated by Django 4.1.3 on 2022-11-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_users_pay_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
