# Generated by Django 4.1.3 on 2022-11-11 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import firstApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_users_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='firstAppUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=100)),
                ('target_url', models.CharField(max_length=2000)),
                ('shortened_url', models.CharField(default=firstApp.models.firstAppUrls.rand_string, max_length=6)),
                ('created_via', models.CharField(choices=[('web', 'Website'), ('telegram', 'Telegram')], default='web', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
